### ISSUE TITLE
R-Syntax SIG

### ISSUE THREAD

**Issue by nickhaf** [iqb-research/IQB-Methods#1]
- (ein) Ziel: nicht immer nur von Jahr zu Jahr alte Syntaxen zu recyclen, sondern aktuellere Routinen zumindest berücksichtigen/kennenlernen
- SIG-Ordner auf T:\SIG\SIG R-Syntax
- Alte Materialien auf i:\Methoden\01_IQB-interne_R_Workshops\alte Workshops\R_Selbsthilfegruppe_BB_17_18_19\
- Methoden-Gruppe wird auf dem Laufenden gehalten

ggf. EG miteinbeziehen

**Comment by franikowsp** [comment]
Finde ich richtig gut! Finde das Format als _Blog_ auch geeignet (z. B. dann so: https://quarto.org/docs/websites/website-blog.html?). Wenn man ein _Book_ aufsetzt, hätte das ja immer so einen Vollständigkeitsanspruch (und würde die Vor-/Nachbereitung ggf. aufwendiger machen). 🤔

**Comment by franikowsp** [comment]
Das größere Thema könnte dann aber die Veröffentlichungsform sein - man kann es ja leider nicht geschützt über z. B. GitHub-Pages releasen, oder? Man könnte alternativ aber den erstellten Blog auf T:/ ablegen... Wäre dann ein weniger echtes Blog-Feeling, aber als Alternative, falls "sensible" Sachen dort thematisiert werden, auf die theoretisch nicht jede beliebige Person Zugriff haben sollte?

**Comment by nickhaf** [comment]
Da könnte man z.B. auch den Newsletter drauf hosten, da muss natürlich drauf geachtet werden dass da nichts sensibles vorkommt und überlegen, wie man darauf verlinkt. Vielleicht wirklich ein Ordner auf T:/ anlegen für sensible Daten, und online dann nur den Pfad zur Verfügung stellen? Anyways, schaut gerne mal rüber wie euch das bisher so gefällt, und ob wir das weiter verfolgen wollen. Ich werds auf alle Fälle für die SIG mal eine Weile ausprobieren.

**Comment by beckerbenj** [comment]
Sieht sehr schick aus! Meine Gedanken/Anmerkungen:
- könnte man unsere R-Tutorials aus dem Wiki mit drauf packen? (http://iqbstaff.pbworks.com/w/page/139033431/R%20Tutorials)
- ich würde mir mit dem Anlegen von Seiten bzw. der Nachbereitung nicht zuu viel Aufwand machen; erfahrungsgemäß schauen eher selten Leute drauf => vlt. ändert sich das aber durch das neue Format auch?
- bisher enthält der Newsletter ja nichts sensibles, da würde ich keine Hindernisse sehen
- einzige Einschränkung: habe aktuell die Hoffnung dass mehr Leute den Newsletter sehen, dadurch dass es direkt eine Mail ist und man nicht irgendwohin klicken muss. Können wir gerne aber auch in der Runde diskutieren

**Comment by nickhaf** [comment]
> könnte man unsere R-Tutorials aus dem Wiki mit drauf packen? (http://iqbstaff.pbworks.com/w/page/139033431/R%20Tutorials)
Klar, habt ihr irgendwo Markdown Datein dafür rumliegen?

> einzige Einschränkung: habe aktuell die Hoffnung dass mehr Leute den Newsletter sehen, dadurch dass es direkt eine Mail ist und man nicht irgendwohin klicken muss. Können wir gerne aber auch in der Runde diskutieren
Vielleicht macht man beides? Theoretisch kann man die Blogs auch abonnieren, dann würde es eine Benachrichtigungsmail geben wenn es was neues gibt. Zumindest könnte man die Newsletter auf der Webseite sammeln.

**Comment by franikowsp** [comment]
Das sieht echt schon richtig gut aus - danke, dass Du das schon einmal umgesetzt hast! 

Ich finde auch für die Startphase beides gut (Newsletter per Mail + auf der Website; ggf. auch mit Abo [könnte aber dann in Spam ausarten für diejenigen, die ohnehin in unserem Verteiler sind?]) - man könnte dann zwischenzeitlich nochmal evaluieren, ob ein Outlet ausreicht? (Ihr macht ab und an mal User-Befragungen, hatte ich gesehen?)

**Comment by beckerbenj** [comment]
>   >  könnte man unsere R-Tutorials aus dem Wiki mit drauf packen? (http://iqbstaff.pbworks.com/w/page/139033431/R%20Tutorials)

> Klar, habt ihr irgendwo Markdown Datein dafür rumliegen?

Ich glaube die .Rmd Files finden sich hier:
i:\Methoden\01_IQB-interne_R_Workshops\R_Einfuehrung_aktuell\Material\

> Ich finde auch für die Startphase beides gut (Newsletter per Mail + auf der Website

Finde ich auch gut!

**Comment by franikowsp** [comment]
Besprechung (01.09.): @nickhaf bastelt daran rum; später ggf. Sichtung von Tutorials durch alle. Später auch Werbung dafür!

**Comment by grewered** [comment]
soll die Seite eigentlich auf deutsch oder Englisch geschrieben sein?

**Comment by beckerbenj** [comment]
@nickhaf hat die ersten Sachen ja alle auf Englisch geschrieben und wir haben am Institut auch einzelne Personen, die nur bedingt Deutsch sprechen. Also gerne wenn es passt auf Englisch 👍

**Comment by beckerbenj** [comment]
https://iqb-research.github.io/IQB-Methods/

**Comment by beckerbenj** [comment]
@grewered pflegt die Base-R-Tutorials ein, die im Wiki liegen. Source RMarkdown Code siehe hier:
i:\Methoden\01_IQB-interne_R_Workshops\R_Einfuehrung_aktuell\Material\

**Comment by beckerbenj** [comment]
NH organisiert Termin um strategische Entscheidungen zu treffen (was ins Wiki, was auf Webpage, ...)

**Comment by grewered** [comment]
BB hatte mir diese Folien zu unter anderem Funktionen schreiben gegeben (Einführung in function()-Funktion + unit testing etc.). kann man die hochladen @beckerbenj? bzw. in welchem Format? weil aktuell sind das einfach normale PowerPoint Folien.

[slides_functions_errors.pdf](https://github.com/iqb-research/IQB-Methods/files/13514810/slides_functions_errors.pdf)

**Comment by beckerbenj** [comment]
@grewered :
Diese Folien sind Teil des Advanced-R Workshops von Dries und mir und liegen (wie alle anderen FDZ-Workshops) auf i:/Methoden ab. Wenn das für euch ok ist, würde ich es dabei erst einmal belassen. Perspektivisch überlegen Dries und ich, unsere Workshop-Materialien auch öffentlich zu hosten (ähnlich dem was Nicklas & Co. mit ihren Workshop-Materialien machen), dann könnte man sie ggf. verlinken.

**Comment by nickhaf** [comment]
Migrated todos into seperate issues in the website project.
