### ISSUE TITLE
Contact Person for each eat-package

### ISSUE THREAD

**Issue by grewered** [iqb-research/IQB-Methods#152]
@iqb-research/methoden Wen soll ich als Kontaktperson für die eat-Pakete eintragen? Und was soll da dann hin? Der Name und die Emailadresse? oder nur der Name?
gemeint sind die Infos auf dieser Seite: 
https://iqb-research.github.io/IQB-Methods/posts_help.html

**Comment by weirichs** [comment]
Auf der Seite stehen ja schon die Abkürzungen der zuständigen Personen. Genau die würde ich auch als Kontakte eintragen, in der Reihenfolge, wie sie dort bereits aufgelistet sind. Ich würde Name und e-mail-Adresse insetzen, wobei zu überlegen wäre, die Mailadresse mit name[at]iqb.hu-berlin.de anstatt name@iqb.hu-berlin.de anzugeben, weil das dann besser vor SPAM schützt? Hier bin ich mir aber nicht sicher ... auf der [IQB-Mitarbeiterseite](https://www.iqb.hu-berlin.de/institut/staff/) steht ja auch das @-Zeichen.

**Comment by grewered** [comment]
> Auf der Seite stehen ja schon die Abkürzungen der zuständigen Personen. Genau die würde ich auch als Kontakte eintragen, in der Reihenfolge, wie sie dort bereits aufgelistet sind. Ich würde Name und e-mail-Adresse einsetzen, wobei zu überlegen wäre, die Mailadresse mit name[at]iqb.hu-berlin.de anstatt [name@iqb.hu-berlin.de](mailto:name@iqb.hu-berlin.de) anzugeben, weil das dann besser vor SPAM schützt? Hier bin ich mir aber nicht sicher ... auf der [IQB-Mitarbeiterseite](https://www.iqb.hu-berlin.de/institut/staff/) steht ja auch das @-Zeichen.

mit oder ohne Link zu den Mitarbeitenden Profilen von der IQB Webseite?

**Comment by sachseka** [comment]
Gerne mit Link zur Mitarbeiterseite oder alternativ (ggf. Stumis?) Link zur Github-Seite...
