### ISSUE TITLE
Put methods team R tutorials on website

### ISSUE THREAD

**Issue by nickhaf** [iqb-research/IQB-Methods#2]
Look here: http://iqbstaff.pbworks.com/w/page/139033431/R%20Tutorials

The markdown-files for the tutorials should lie on i:\Methoden\ 

**Be careful not to upload data that is not openly available. Also only use the tutorials created by the Methods-Team for now, so we can be sure we are allowed to upload them (for example, there is a folder for the FDZ-Workshops by external creators, we probably would have to ask them if we are allowed to upload).**

**Comment by grewered** [comment]
3 German R Turotials from here (http://iqbstaff.pbworks.com/w/page/139033431/R%20Tutorials) are online now. 
For the others: we still have to ask the creators whether they would be ok with publishing it.
