### ISSUE TITLE
Write chapter with an explanation of how to update the website.

### ISSUE THREAD

**Issue by nickhaf** [iqb-research/IQB-Methods#25]

**Comment by beckerbenj** [comment]
Aktuell noch buggy, wird nächste Woche gefixed

**Comment by beckerbenj** [comment]
Offene Frage: Tauchen Änderungen auf der Homepage auf, auch wenn sie nur in einem devel-Branch sind? @nickhaf

**Comment by nickhaf** [comment]
Bug gefixed, AA reviewed noch.
