### ISSUE TITLE
PARED_imp in BT21&BT22 neu für GADS

### ISSUE THREAD

**Issue by sachseka** [iqb-research/IQB-Methods#30]
Die passive Imputation der Variable war in beiden BTs buggy. Die Variable lässt sich aber direkt aus HISCED_imp rekodieren ("0=0;1=4;2=10;3=13;4=13;5=15;6=18"). Für BT21 aus Ehisced_imp mache Epared_imp, in BT22 aus KHISCED_imp mache KPARED_imp. Benjamin noch vor seiner Elternzeit um Einfgen/Unterstützen bei Einfügen bitten.

**Comment by beckerbenj** [comment]
für BT22 erfolgt
für BT21 im Prinzip auch, Tests stehen noch aus
