### ISSUE TITLE
Build Learn - Site

### ISSUE THREAD

**Issue by nickhaf** [iqb-research/IQB-Methods#90]
- Should be a [Grid](https://quarto.org/docs/websites/website-listings.html#listing-types), where tutorials, and texts for Wissensvermittlung are collected. 
- Should have a site-specific left side navigation with collapsed headers structuring the content a bit more. 
- On the right side, categories (tags) should be collected, where users can filter according to areas of interest. 
- Grid-specific Searchfield above the grid

**Comment by grewered** [comment]
we could also add multiple grids on one page, apparently:
![grafik](https://github.com/user-attachments/assets/7a602f4e-8f06-479d-bed6-f9366340321f)

**Comment by grewered** [comment]
**to do**

- [ ] collect all tutorials, r-sig pages and FAQ files in 1 (posts) folder
- [ ] delete the individual pages (on the left side and navbar)
- [ ] create 1 new `learn` page in navbar with grid (default)
- [ ] all files should have: tags (r-sig, FAQ, R tutorial, checkmate, renv, etc.)
- [ ] *create seperate .qmd files for different FAQ answers*
- [ ] create side specific left side navigation - with collapsed headers for structuring the content
- [ ] add grid-specific Searchfield above the grid

new page shall contain content from the pages: 

- r-sig 
- FAQ
- internal documentation (website, *code conventions*)
- rest of left side nav: r tutorials, renv, checkmate, github

**Comment by grewered** [comment]
add these to some .qmd file?

![grafik](https://github.com/user-attachments/assets/c15ad9f4-bac5-4825-9944-16a4a14ba8f5)
https://nickhaf.github.io/r_tutorial/
https://iqss.github.io/dss-workshops/R/Rintro/base-r-cheat-sheet.pdf

**Comment by grewered** [comment]
to dos

- [ ] add short descriptions in yaml header
- [ ] split FAQ file
- [ ] look for FAQ images and add descriptions.
