### ISSUE TITLE
Build packages page

### ISSUE THREAD

**Issue by nickhaf** [iqb-research/IQB-Methods#94]
- Remove tables and intermediate landing pages. Instead we want cards with the package thumbnail, a short description and the package authors. When clicking on the card, the user lands on one of the following pages, in order of importance:

1. Bookdown
2. CRAN
3. GitHub

**Comment by grewered** [comment]
- [ ] write listing in yaml header on index page
- [ ] add info from 'eat package info'
- [ ] collect the bookdown, CRAN or Github pages/links
- [ ] get the stickers for the default listing image
- [ ] short info on listing-Kachel: Sticker, package name, author/contact, short description
- [ ] figure out how to have a listing that links directly to another website

**Comment by grewered** [comment]
It looks like those links link to other pages. 

![grafik](https://github.com/user-attachments/assets/9d0b0a05-5f37-4053-aec3-61708b664bab)

**Comment by grewered** [comment]
some more possible solutions: 

- https://quarto.org/docs/websites/website-listings-custom.html
- https://github.com/quarto-dev/quarto-cli/discussions/6338
- https://github.com/quarto-dev/quarto-cli/discussions/7376
-
