### ISSUE TITLE
Build Help - Site

### ISSUE THREAD

**Issue by nickhaf** [iqb-research/IQB-Methods#97]
Currently not that much content. could contain help for the packages, like links to the documentations, frequently asked question (with short answers, e.g. what to do when some special error message appears). Also link to gitHub issues and mail adresses of the package authors.

**Comment by grewered** [comment]
https://bootswatch.com/sandstone/
here are some examples for Cards/Boxes and accordions (the one, where you drop down/open to more text). relative down the bottom.

**Comment by grewered** [comment]
structure: 

- shorter FAQ (with accodions/drop down answers)
- emails package authors (table?) + ggf. documentations (reduce redundancy, just link to the eat-page)
- ggf. links to github issues

**Comment by grewered** [comment]
adding accordion/drop down answers:
simple: https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab
